### ISSUE TITLE
Since this is written is node.js there should be a guide to show how to run this on a local machine.

### ISSUE THREAD

**Issue by mohsini172** [asadm/urduscript#1]

**Comment by asadm** [comment]
You are right. I plan to fix some things and make this into an npm package soon.

**Comment by HammadSiddiqui** [comment]
I'm sending in a pull request for this one

**Comment by asadm** [comment]
@HammadSiddiqui most welcome! Care to outline how you plan to do this?

**Comment by asadm** [comment]
Never mind. The above instructions are if one wants to run from command line. Thanks!
