### ISSUE TITLE
npm start gives error

### ISSUE THREAD

**Issue by muzammil17** [asadm/urduscript#6]
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error urdu.js@1.0.0 start: `cp src/keywords.js docs/editor/scripts/urdujs/keywords.js.txt && node_modules/nws/bin/nws -d docs/editor`
22 error Exit status 1
23 error Failed at the urdu.js@1.0.0 start script 'cp src/keywords.js docs/editor/scripts/urdujs/keywords.js.txt && node_modules/nws/bin/nws -d docs/editor'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the urdu.js package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cp src/keywords.js docs/editor/scripts/urdujs/keywords.js.txt && node_modules/nws/bin/nws -d docs/editor
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs urdu.js
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls urdu.js

This is the error that gets printed in the npm debug file. There's seem to be a problem with the start script in the package.json

**Comment by asadm** [comment]
can you try running: `node_modules/nws/bin/nws -d docs/editor` in the terminal and see if it works?

**Comment by asadm** [comment]
I have updated the instructions in the Readme. They should work now for windows. Closing for now.
